baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sudarshan Vankudre'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Sudarshan Vankudre"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm a software engineer who enjoys building things. 
"""

# Collection to display on home
homeCollectionTitle = "Projects"
homeCollection = 'projects'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sudarshanvankudre/"

[[params.social]]
name = "github"
url = "https://github.com/sdrshnv"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "projects"
# url = "/projects"

# [[params.menu]]
# name = "resume"
# url = "/resume.pdf"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
